apiVersion: v1
kind: Service
metadata:
  name: {{ include "exampleapp.fullname" . }}
  labels:
    {{- include "exampleapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "exampleapp.selectorLabels" . | nindent 4 }}
    component: deployment
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "exampleapp.fullname" . }}-ss
  labels:
    {{- include "exampleapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "exampleapp.selectorLabels" . | nindent 4 }}
    component: statefulset
